# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graymatter < Formula
  desc "Persistent memory for AI agents. Single binary, zero infrastructure."
  homepage "https://github.com/angelnicolasc/graymatter"
  version "0.16.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/angelnicolasc/graymatter/releases/download/v0.16.4/graymatter_0.16.4_darwin_amd64.tar.gz"
      sha256 "42fadaac8554321065e0ddb509bf3028a04997f91833b621df33f31565f8d2ba"

      define_method(:install) do
        bin.install "graymatter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/angelnicolasc/graymatter/releases/download/v0.16.4/graymatter_0.16.4_darwin_arm64.tar.gz"
      sha256 "74e511322857f4e777bc2c2f89677ac79131d19c8b24fea299286938b4ff5605"

      define_method(:install) do
        bin.install "graymatter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/angelnicolasc/graymatter/releases/download/v0.16.4/graymatter_0.16.4_linux_amd64.tar.gz"
      sha256 "a6027b6a3337c222cb6ce60ce36796c0a5e4a038f83deaa730227147640fc98b"
      define_method(:install) do
        bin.install "graymatter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/angelnicolasc/graymatter/releases/download/v0.16.4/graymatter_0.16.4_linux_arm64.tar.gz"
      sha256 "4049335690ab08533ff196b0f5a6b4e3ea910c79c85261e360b32e4e29cc77ae"
      define_method(:install) do
        bin.install "graymatter"
      end
    end
  end
end
